name: fm_mahanama_mobile_app
description: Official FOSS FM Mahanama mobile app for IOS and Android created with Flutter
publish_to: 'none'

version: 0.0.1-beta

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gradient_colors: ^2.1.1
  url_launcher: ^6.1.11
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_crashlytics: ^3.3.2
  firebase_storage: ^11.2.2
  firebase_performance: ^0.9.2+2
  font_awesome_flutter: ^10.4.0
  assets_audio_player: ^3.0.6
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  profanity_filter: ^2.0.0
  package_info_plus: ^4.0.2
  icons_launcher: ^2.1.1
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

icons_launcher:
  image_path: "assets/icons/ic_logo_border.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icons/ic_logo_border.png"
      adaptive_background_color: '#FFD600'
      adaptive_foreground_image: "assets/icons/ic_foreground.png"
      adaptive_round_image: "assets/icons/ic_logo_round.png"
      adaptive_monochrome_image: "assets/icons/ic_logo_monochrome.png"
    ios:
      enable: true
      image_path: 'assets/icons/ic_logo_rectangle.png'
    web:
      enable: false
    macos:
      enable: false
    windows:
      enable: false
    linux:
      enable: false

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/ic_logo_round.png
  android_12:
    image: assets/icons/ic_foreground.png
    color: "#ffffff"
    icon_background_color: "#FFD600"
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  android_screen_orientation: sensorPortrait
  fullscreen: true