// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEK7diFKSH5-q2yVlqLhfBgFNRRzPPztU',
    appId: '1:1023337101903:android:81a9eff4d325802937483a',
    messagingSenderId: '1023337101903',
    projectId: 'fm-mahanama-2017-live-stream',
    databaseURL: 'https://fm-mahanama-2017-live-stream.firebaseio.com',
    storageBucket: 'fm-mahanama-2017-live-stream.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxtQyWjAW6U5-ztITihlaJYH4z3KI_r-0',
    appId: '1:1023337101903:ios:391bb1b7c247ed7737483a',
    messagingSenderId: '1023337101903',
    projectId: 'fm-mahanama-2017-live-stream',
    databaseURL: 'https://fm-mahanama-2017-live-stream.firebaseio.com',
    storageBucket: 'fm-mahanama-2017-live-stream.appspot.com',
    androidClientId: '1023337101903-01dngqutq50pqvfs1h87903grur5kd1s.apps.googleusercontent.com',
    iosClientId: '1023337101903-bdgci3is26anglj1nlu3t069ugv5vpkh.apps.googleusercontent.com',
    iosBundleId: 'lk.com.rusiruwijethilake.fmMahanamaMobileApp',
  );
}
